### ISSUE TITLE
ajv-oai does not check type correctly

### ISSUE THREAD

**Issue by mknj** [oaijs/ajv-oai#9]
I would expect that ajv-oai  and ajv return the same result for the following types.
I would also expect that nullable:false means null is not accepted.

# versions
node_modules/ajv-oai/package.json:  "version": "1.2.0"
node_modules/ajv/package.json:  "version": "6.12.5"

# code
```js
const Ajv = require('ajv')
const ajv = new Ajv();
const Ajvoai = require('ajv-oai')
const ajvoai = new Ajvoai();

console.log(ajv.compile({ type: 'number' })("42"));
console.log(ajv.compile({ type: 'string' })(42));
console.log(ajv.compile({ type: 'string' })(null))

console.log(ajvoai.compile({ type: 'number' })("42"));
console.log(ajvoai.compile({ type: 'string' })(42));
console.log(ajvoai.compile({ type: 'string', })(null));
console.log(ajvoai.compile({ type: 'string', nullable: false })(null));
```
# expected output
```
false
false
false
false
false
false
false
```
# actual output
```
false
false
false
true
true
true
true
```

**Comment by mknj** [comment]
just found out that you can do 
```
const ajvoai = new Ajvoai({ coerceTypes: false });
```
Please document in the readme.md that ajvoai uses different default options.

**Comment by amazing-gao** [comment]
Thanks for issue.
`ajv-oai` sets `coerceTypes` `true` as default.
Your can see [Ajv type coercion rules](https://github.com/ajv-validator/ajv/blob/master/COERCION.md).
I will update readme.md.
